version: '3.9'
services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: odyssey
      POSTGRES_USER: odyssey
      POSTGRES_PASSWORD: odyssey
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: ["gunicorn", "odyssey.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "3", "--threads", "3"]
    environment:
      DJANGO_SECRET_KEY: dev-secret
      DJANGO_DEBUG: "1"
      DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1
      DATABASE_URL: postgres://odyssey:odyssey@db:5432/odyssey
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata:
