# Generated by Django 5.2.6 on 2025-09-18 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='importance',
            field=models.IntegerField(default=1, help_text='1 (Low) to 5 (High)'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='urgency',
            field=models.IntegerField(default=1, help_text='1 (Low) to 5 (High)'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='epic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.epic'),
        ),
    ]
