# Generated by Django 5.2.6 on 2025-09-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_updated_by_alter_ticket_importance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sort_order',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
