# Generated by Django 5.2.6 on 2025-09-19 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_usertheme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketactivity',
            old_name='action',
            new_name='activity_type',
        ),
        migrations.RenameField(
            model_name='ticketactivity',
            old_name='details',
            new_name='description',
        ),
    ]
