# Generated by Django 5.2.6 on 2025-09-20 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_rename_action_to_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent ticket in hierarchy (Epic for tickets, Ticket for bugs).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='related_tickets',
            field=models.ManyToManyField(blank=True, help_text='Non-hierarchical linked tickets.', related_name='related_from', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('epic', 'Epic'), ('ticket', 'Ticket'), ('bug', 'Bug')], db_index=True, default='ticket', help_text='Categorizes this ticket in the hierarchy.', max_length=10),
        ),
    ]
