# Generated by Django 5.2.6 on 2025-09-20 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_convert_epic_to_ticket_epics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='epic',
        ),
        migrations.DeleteModel(
            name='Epic',
        ),
    ]
